### ISSUE TITLE
flycheck issues shown for lines that are not causing the errors

### ISSUE THREAD

**Issue by dakrone** [mopemope/meghanada-emacs#10]
I have meghanada enabled for a particular buffer, and it shows this flycheck error:

```
    45  13 error           cannot find symbol
   symbol:   method availableUnless(joptsimple.OptionSpec<java.lang.Void>)
   location: class joptsimple.OptionSpecBuilder (meghanada)
```

However, if I hit `RET` or go to that exact line, the Java code is:

``` java
import org.elasticsearch.Version;
```

It seems like the line number might be correct, but it is probably for a different buffer than the current buffer.

(It's also strange, as I have 7 errors from a project that passes `gradle compileJava compileTestJava` cleanly when I run from the CLI)

**Comment by mopemope** [comment]
Please try again after delete `.meghanada` directory or call `M-x meghanada-clear-cache`.

**Comment by zhihuiFan** [comment]
I run into the same issue here and tried both delete .meghanada and meghanada-clear-cache, it is still there.  however I can run 'meghanada-exec-main' at that case.

what shall i do next?
