### ISSUE TITLE
consider support gradlew?

### ISSUE THREAD

**Issue by Habens** [mopemope/meghanada-emacs#104]
If the project contains the Gradlew, I prefer running gradle task via Gradlew, rather than the Gradle.

**Comment by mopemope** [comment]
@Habens yes. supported.

**Comment by Habens** [comment]
@mopemope 
aah, not sure what you mean `supported`. there is `gradlew` file in my project.  the `, l t b` (run current buffer test) result is:

```
/usr/local/bin/gradle test -Dtest.single=xxxx
...
```
The task runing via `gradle`, rather than `gradlew`.

BTW, This [issue](https://github.com/jacobono/emacs-gradle-mode/issues/8) should be from [emacs-gradle-mode](https://github.com/jacobono/emacs-gradle-mode), which dependes by `meghanada`. And there is a [pull request](https://github.com/jacobono/emacs-gradle-mode/pull/11) to optimize project's gradlew.

**Comment by mopemope** [comment]
Meghanada used gradle tooling API (meghanada-run-task function) . It has nothing to do with emacs-gradle-mode.
The API automatically decides to use gradlew preferentially and executes it.

**Comment by Habens** [comment]
umm, sorry this issue make u confused. I checked the issue more carefully, that issue is not part of this repos.
I misunderstand the Spacemacs java layer's behavior, I thought the `, l t b` will invoke Meghanada first, than Meghanada manage the gradle task.  Actully, `, l t b` directlly bind with `emacs-gradle-mode`.
Thanks for you quick response.
