### ISSUE TITLE
Meghanada eat all my CPU

### ISSUE THREAD

**Issue by azzamsa** [mopemope/meghanada-emacs#105]
I know that Netbeans/Eclipse eat lot of CPU at startup. But why meghanada eat my CPU almost at short interval. Is that because my code changes and meghanada indexing ?

Is it normal to eat all that CPU resources ? (this often happens to me)

![2018-05-30-15 24 22](https://user-images.githubusercontent.com/17734314/40708633-290904da-641e-11e8-819c-61e63fa94282.png)

Thanks for Meghanada :)

**Comment by mopemope** [comment]
Yes. It does indexing on saving. And then it caches the completion candidate at idle time.
Probably, I think that processing at idle is consuming CPU, so I will fix it.

**Comment by azzamsa** [comment]
> Yes. It does indexing on saving

Oh. it use save event. I use super-save. that's why it always indexing. Cause super-save automatically save buffer when it's not in focus.

other than that. Java ecosystem is always using a lot of cpu. It's not meghanada mistake per se.

**Comment by mopemope** [comment]
@azzamsa @iquicktest  Fix it. please check latest version.

**Comment by azzamsa** [comment]
Yes. I saw the update last night. 

Just tried it. Meghanada use lot CPU usage at first indexing. But I think it's normal. Since other java tools e.g Netbeans, Eclipse also use lot CPU usage.

It comes to normal when the indexing finished. I tried completion, and no high CPU consumption occurred. 

I will report if anything bad happened :)

Thank you for Meghanada.

**Comment by iquicktest** [comment]
Cool. Thanks @mopemope
