### ISSUE TITLE
Java style settings

### ISSUE THREAD

**Issue by l7ssha** [mopemope/meghanada-emacs#107]
Hello, there is any way to customize java style settings.
For example I'm using 4 spaces - meghanada forces 2 spaces or I never bother about column width - meghanada moves my constructor variables to new line, or new line in javadoc comments,

~~I didn't found informations about that, so there is issue.~~

![image](https://user-images.githubusercontent.com/23033957/40879907-3db17d2c-66a8-11e8-8040-4ddbb50a3d36.png)

Arch Linux, 4.16.9-1-ARCH
Latest meghanada, latest emacs

**Comment by l7ssha** [comment]
TO CLOSE. I didn't read readme.md good enough. There is heading about formatting: [https://github.com/mopemope/meghanada-emacs#customize-code-formatter](https://github.com/mopemope/meghanada-emacs#customize-code-formatter)

**Comment by mopemope** [comment]
@l7ssha Fixed https://github.com/mopemope/meghanada-server/issues/64
