### ISSUE TITLE
Meghanada server never starts

### ISSUE THREAD

**Issue by l7ssha** [mopemope/meghanada-emacs#109]
After opening new project meghanada says 'Meghanada-Server Starting' and it never starts.

Tried deleting meghadanda, redownloading server, recreating project, tested on different projects - it always tries to start server and never do this. 

Some logs from `*messages*` buffer:
```
launch server cmd:java -Djava.net.preferIPv4Stack=true -Dmeghanada.class.completion.matcher=prefix -Dmeghanada.completion.matcher=fuzzy -Dmeghanada.format=sexp -Dmeghanada.cache.in.project=true -Dmeghanada.skip.build.subprojects=true -Dmeghanada.full.text.searchs=true -Dmeghanada.search.static.method.classes=java.util.Objects,org.junit.Assert -Dmeghanada.javac.arg=-Xlint:all -Dmeghanada.maven.path=mvn -Xms128m -XX:ReservedCodeCacheSize=240m -XX:SoftRefLRUPolicyMSPerMB=50 -ea -Dsun.io.useCanonCaches=false -Dfile.encoding=UTF-8 -jar /home/l7ssha/.emacs.d/meghanada/meghanada-1.0.4.jar -p 0 
Meghanada-Server Starting ...
```

latest meghanada-emacs
meghanada-server: v1.0.4
latest emacs
Arch Linux, 4.16.13-2-ARCH

**Comment by mopemope** [comment]
@l7ssha Please check `meghanada-server-log` buffer.

**Comment by l7ssha** [comment]
it's very weird, problem now don't exists - everything starts now just fine.
I can guess it can be my computer fault - don't know.
Whatever - to close.
