### ISSUE TITLE
Server exits almost immediately

### ISSUE THREAD

**Issue by udalrich** [mopemope/meghanada-emacs#11]
After installing, I entered a buffer in jdee-mode, which derives from java-mode.  I did `M-x meghanda-mode`.  A few seconds later, these messages where in my messages buffer.

    Meghanada-Server Starting ...
    Meghanada-Server Started
    meghanada-server process stopped
    client connection not established

Attempting to restart the server with `M-x meghanda-server-start` gave the same result.

I am running Emacs 24.5.1 on Mac OS X.  
GNU Emacs 24.5.1 (x86_64-apple-darwin14.5.0, NS apple-appkit-1348.17)

**Comment by mopemope** [comment]
I have fixed it. Please check latest version. and call `M-x meghanada-install-server`.
