### ISSUE TITLE
Ability to set JVM proxy

### ISSUE THREAD

**Issue by hackeryarn** [mopemope/meghanada-emacs#117]
It would be really nice to have an easily configurable way to set proxy settings. Currently only way to accomplish this to modify the `meghanada-server-jvm-option`.

The options that would need to be set are `DsocksProxyHost` and `DsocksProxyPort`

**Comment by hackeryarn** [comment]
I would be happy to work on this, just wanted to make sure this is something you are interested in adding.

**Comment by mopemope** [comment]
@hackeryarn Please use `meghanada-jvm-option`.
