### ISSUE TITLE
Does meghanada track packages??

### ISSUE THREAD

**Issue by blutics** [mopemope/meghanada-emacs#118]
It seems to track every classes, but not packages.
when I type 'import java.', it doesn't give any options in that package through company-pop.
Is there any way to make it tracking packages??

**Comment by mopemope** [comment]
@blutics Please enter the class name directly.

![screenshot from 2018-08-23 14-45-19](https://user-images.githubusercontent.com/22645/44506853-38785f80-a6e3-11e8-81e8-0308a170889b.png)
