### ISSUE TITLE
Allow code completion in annotation fields and value

### ISSUE THREAD

**Issue by iocanel** [mopemope/meghanada-emacs#130]
Assuming that I have the following annotation:

     public @interface Param {
         String key();
         String value();
     }

When using it, I would expect to have completion at `@Param(ke` but I don't.

**Comment by mopemope** [comment]
Supported it.
![anno](https://user-images.githubusercontent.com/22645/50887321-3ca8dd80-1436-11e9-9a0b-d8000d05dd60.png)
