### ISSUE TITLE
Support Checkstyle As A Flycheck Source

### ISSUE THREAD

**Issue by tekktonic** [mopemope/meghanada-emacs#132]
Flycheck currently only shows complaints from the java compiler. I use meghanada for work and need to manually run checkstyle over all of my code. It would be much easier if the user could just define some meghanada-checkstyle-command variable which would be used to feed into flycheck as well as the compiler.

**Comment by mopemope** [comment]
@tekktonic I have no plans to support it.Instead, I think that you can use it.
https://github.com/leeaustinadams/flycheck-checkstyle
