### ISSUE TITLE
Meghanada Spams Minibuffer With "meghanada ready"

### ISSUE THREAD

**Issue by tekktonic** [mopemope/meghanada-emacs#135]
It seems to be nondeterminstic, but occasionally meghanada seems to get in a bad state and instead of offering information in the minibuffer it just keeps spamming "meghanada ready". I can't get it to reproduce consistently, but it seems to happen pretty often. Running openjdk 1.8.0_192, emacs 25.3.1

**Comment by mattroid** [comment]
+1 This happens to me quite often too. I'm running emacs 26.1 and jdk 1.8
