### ISSUE TITLE
Allow an alternative server location

### ISSUE THREAD

**Issue by akirak** [mopemope/meghanada-emacs#137]
I was unable to fetch the jar file of meghanada from my workplace. It might be because https://bintray.com/ is considered a harmful site, even if your package itself isn't harmful and may be even useful for work.

Please make sure that the package source is customizable (like deb/yum/etc. is), so people can download the software from other servers.

This possibly relates to #37 and #92.

**Comment by fdagnat** [comment]
Is there a way to install manualy the server? I have downloaded it, built it and copied the jar to the .emacs.d/meghanada directory but the meghanada-server-start still does not work, it says I should use meghanada-install-server which gives a connection error for the bintray server.

**Comment by fdagnat** [comment]
Ok, find out that on macos, we must use the directory `~/Library/Preferences/Aquamacs\ Emacs/Packages/meghanada` instead of `emacs.d/meghanada`.

**Comment by akirak** [comment]
I added an experimental support for this feature in https://github.com/mopemope/meghanada-emacs/pull/142. I am still unable to download the jar file automatically due to my office network.

**Comment by akirak** [comment]
You have added an instruction for manually installing `meghanada-setup-XXX.jar`, but the setup program fails to download the server jar in my network. Maybe you have to either fix the setup jar or re-implement the downloading logic in this package.

**Comment by akirak** [comment]
I have created a new pull request https://github.com/mopemope/meghanada-emacs/pull/143 which doesn't need `meghanada-setup-XXX.jar` to download `meghanada-XXX.jar`. It directly download the server program.
