### ISSUE TITLE
No autocompletion for instance methods?

### ISSUE THREAD

**Issue by sandric** [mopemope/meghanada-emacs#14]
I just want to understand if thats only my issue or its how mode supposed to work as for now. I have only keywords and class names autocompletion, but if I try to autocomplete with dot instance of `List<String>` - I get only keywords that was entered before (abbrev I think) - and no actual instance methods of `List` class. So is this is all ok, or I made smth wrong and thats an error?

**Comment by mopemope** [comment]
Please check `mode-string`. And see `*meghanada-server-log*` buffer.

**Comment by sandric** [comment]
@mopemope Sorry, I can't see `mode-string` via describe-variable and describe-function, and `(print mode-string)` gives me `void variable`, how should I check it?
As for server-log buffer, you right, after attempting to autocomplete instance I getting
```
[2016-09-29 17:42:17,441][ERROR][JavaCompletion:  44] completionAt           - null
java.lang.NullPointerException
```

**Comment by sandric** [comment]
Hm now I'm totally confused, I just opened `meghanada-server/src/main/java/meghanada/main.java` and tried to autocomplete `version` `String` type instance variable and seems like it works, but after trying to add in the same function
```java
final List<String> list = new ArrayList<>();
list.
```
gives me an abbrev autocompletion without actual methods. Seems strange.

**Comment by mopemope** [comment]
Meghanada will analyze symbol and call method, after save buffer.
try following.

```
final List<String> list = new ArrayList<>();
<save>
list.
```

**Comment by sandric** [comment]
Hey looks it works, thanks a lot!
Also havent you thought about change that behavior to copy buffer contents each time buffer gets changed to tmp file and feed server that file? Its how its done in emacs-sourcekitten for example. Is there a way to somehow feed meghanada buffer instead of file for not to save?

**Comment by mopemope** [comment]
I don't know ` emacs-sourcekitten` ... Contributions are extremely welcome.
