### ISSUE TITLE
Possible bug when starting server

### ISSUE THREAD

**Issue by bsless** [mopemope/meghanada-emacs#145]
Hello,
I was unable to run `meghanada-server-start` and kept getting an error related to a void symbol. After some debugging I think I found the culprit:
in `meghanada--start-server-process` the variable `temporary-file-directory` is invoked as a function, which throws an error
It's a very quick fix, I tried removing the wrapping parentheses and it worked wonderfully.
I don't mind opening a pull request for it if you'd like me to take it.

Emacs: 25.3.1
Spacemacs version: develop 6f6b06
Meghanada version: 20190426.1358
OS: Opensuse 15.0

**Comment by soulawaker** [comment]
Same idea. I've also confirmed.
