### ISSUE TITLE
error handling while downloading jar

### ISSUE THREAD

**Issue by jave** [mopemope/meghanada-emacs#15]
I had some issues downloading the jar with the meghanada-install-server command while being behind an aggressive corporate firewall.

meghanada said the download was okay, but the download had in fact failed.

In the end I had to download and install the jar manually, which is quite okay, because meghanada cant be responsible when theres an aggressive firewall. But it wouldve been nice with an error message.

**Comment by mopemope** [comment]
It is improve error message since 0.2.4. Please try update to 0.2.4.
 
![error](https://cloud.githubusercontent.com/assets/22645/19482763/ff3c0492-958c-11e6-9b91-7ea1b8170144.png)
