### ISSUE TITLE
Can one easily use meghanada to gain an AST?

### ISSUE THREAD

**Issue by wol81** [mopemope/meghanada-emacs#154]
I am implementing some support for my own JavaScript projects in elisp, and came across the need to get information about the methods of a given Java interface (specifically, I want to do completion etc. of Java methods called using JsonRPC from JavaScript).

So, I need the method names and parameter names; return types and argument types would be nice-to-have but are probably less important.

In js2-mode, I can easily gain an abstract syntax tree for a given JavaScript file, my hope was that I can get something similar for a Java file as well, then do some navigation in the AST, and have the information I need.

Now I found meghanada, but when looking into the source code, things doesn't seem to be that simple.  

So, question to you:
- is using meghanada for the task I describe above a reasonable approach?
- I found an outcommented meghanada-parse-file function in source code, and at first glance no other function that simply parses a given java file.  I did a quick test making it active, but it fails with the error I pasted below --- so does it really have a reason why it is outcommented?
- I noticed that meghanada seems to do a lot of tasks in an asynchronous manner (which isn't necessary for me, and just would make my code much more complicate) --- can meghanada used for such things in a synchronous manner as well?
- if meghanada is not what I search for that task, do you have any hints for what elisp code I might use for that task?  An attempt to use jdee quickly failed because it cannot properly process our projects with Java 8 etc. language features...

To make it short,  I'm evaluating what tool I might use for parsing that interface functions... 
(or wether I really need to analyze that interface files using poor-mans search, buffer-substring, etc. handwritten elisp code...)

Thanks for any hints.

Attempt to interactively call outcommented function meghanada-parse-file:
(wrong-type-argument stringp (success))
  message((success))
  apply(message (success) nil)
  meghanada--process-client-response(#<process meghanada-client> "(success (success))")
  #f(compiled-function (r) #<bytecode 0x14b0315>)("(success (success))")
  mapc(#f(compiled-function (r) #<bytecode 0x14b0315>) ("(success (success))"))
  meghanada--client-process-filter(#<process meghanada-client> "(success (success))\n;;EOT\n")

**Comment by mopemope** [comment]
@wol81 As you can imagine, parsing Java code in Elisp is very difficult.
It would be reasonable to let another small Java program analyze it.
I think it's better to use [javaparser](https://github.com/javaparser/javaparser).
