### ISSUE TITLE
meghanada company completion displays also irrelevant entries

### ISSUE THREAD

**Issue by emmanueltouzery** [mopemope/meghanada-emacs#160]
meghanada completion works for me, but it also includes entries which are not relevant. However it's trivial to visually see which entries are relevant: those that are METHOD or FIELD. I don't understand why the other entries are included:

![image](https://user-images.githubusercontent.com/339433/71783634-ceb3d980-2fe9-11ea-9099-18a561533abb.png)

Is there a way for me to filter the completion entries to include only METHODs and FIELDs? am I missing something?

**Comment by mopemope** [comment]
@emmanueltouzery I think it's a good idea to set it up as follows.
```
  (add-hook 'java-mode-hook
            (lambda ()
              (flycheck-mode t)
              (meghanada-mode t)
              ;;; use only meghanada-backend
              (add-to-list 'company-backends 'company-meghanada)
              (add-hook 'before-save-hook (lambda ()
                                            (meghanada-code-beautify-before-save)))))
```
