### ISSUE TITLE
xref interface?

### ISSUE THREAD

**Issue by mohkale** [mopemope/meghanada-emacs#163]
It'd be nice to be able to use xref with `meghanada-mode`. For example, with `lsp-mode` you can run `xref-find-definition` and it'll use the definition given by the lsp-server.

 At the very least I'd like `xref-find-references` `xref-find-definitions` to be implemented, though I'm not sure how xref implements backends.

Thoughts?

**Comment by mopemope** [comment]
@mohkale Support for `xref-find-references` and `xref-find-definitions` in the following versions.

**Comment by mopemope** [comment]
@mohkale I've released the latest version that fixes this issue.
I hope you'll try it.

**Comment by mohkale** [comment]
just tested, seems to be working well. thnx for the great work :smile:.

one weird issue I'm facing is that I keep getting `No definitions found for: %s` messages when I try `xref-find-definitions`... even though it then takes me straight to the definition. Is that expected?

**Comment by mohkale** [comment]
@mopemope ?

**Comment by mopemope** [comment]
@mohkale Sorry it took me so long to get back to you. 
That behavior doesn't seem to be correct. Could you make an issue as that is a separate issue?
