### ISSUE TITLE
Question : is maven mandatory for meghanada-emacs to work ?

### ISSUE THREAD

**Issue by deb75** [mopemope/meghanada-emacs#168]
Hello,

I saw in `meghanada-emacs` a setting for the path to `maven`. Doest it mean it is mandatory for `meghanada-emacs` to work ? Or can it be left blank ?

Regards

**Comment by mopemope** [comment]
Yes. It works even if the setting is empty. 
In this case, run the `mvn` command in the PATH.

**Comment by deb75** [comment]
Hi,

Thanks for your answeer.

I am not sure to have been understood, my question was probably not clear enough.

The question is that I am involved in several projects, some of them are Eclipse project with maven, some others are Eclipse without maven. This has a direct impact on the directory architecture.

So, I wonder whether `meghanada-emacs`, and also `meghanada-server` can adapt itself to different types of projects.

My intuition is that `meghanada` will look at the root directory if there exist a `POM.xml`, if yes it will use maven and if not, it will rely on its `.meghanada.conf` configuration file.

Am I correct ?

Regards

**Comment by mopemope** [comment]
@deb75 Yes.
The project detection priorities are as follows.
1. gradle
2. gradle (kts)
3. maven
4. eclipse
5. meghanada.conf

**Comment by deb75** [comment]
Thanks for these details.

In my Eclipse project there are two dot files at its root : `.classpath` and `.project`. Is it enough for meghanada to detect it is an Eclipse project ? and do I still need to provide a `.meghanada.conf` file ?

Regards

**Comment by mopemope** [comment]
@deb75 Yes. Those two files are sufficient. You don't need the `meghanada.conf` file.

**Comment by deb75** [comment]
Hi,

I manage to get it working, the project is recognized as an eclipse one. However, I had to specify better some paths in the `.meghanada.conf`.

I tried then to run the task "package", but it failed with "(error Not support)". I guest it is because `maven` is no more used in my project. Then, is there a way from `meghanada` to build the jar file ?
