### ISSUE TITLE
[[Inquery]] Method's Arguments Fill-In with Company

### ISSUE THREAD

**Issue by WammKD** [mopemope/meghanada-emacs#169]
I was just wondering how you enabled company filling in the arguments upon auto-completing a method name? Is this a setting of Company Mode that can be enabled and disabled?

Thanks for any help!

**Comment by mopemope** [comment]
The reason I enabled that feature is to check the type of the argument.
I'll add a setting that can be disabled in the next version.

**Comment by mopemope** [comment]
@WammKD I've released the latest version that fixes this issue.
I hope you'll try it.

**Comment by WammKD** [comment]
Oh; heh, that's actually one of my favorite features of Meghanada mode (amongst many). I was inquiring because there's another mode I use that uses Company that I wanted to see if I could get to work the same way.

If it's just a setting or something easy in Company, I was hoping to enable it for that other mode I use.

But I'm sure someone out there might want to disable it in Meghanada so that's probably good that it got added as an option.

**Comment by WammKD** [comment]
Hey, so I pulled the latest and wound up getting this error after completing `.stream()` for an `ArrayList`.

<img width="1280" alt="Screen Shot 2020-05-06 at 5 25 21 PM" src="https://user-images.githubusercontent.com/10533934/81234726-f1b5c080-8fbe-11ea-91f0-6a863486e35d.png">

**Comment by mopemope** [comment]
@WammKD Hmm. I can't reproduce it here...

**Comment by WammKD** [comment]
No worries; I haven't seen it since so I'll probably chock it up to a fluke. Thanks a ton!
