### ISSUE TITLE
compilation-error-regexp-alist setting breaks Maven error detection

### ISSUE THREAD

**Issue by dventimi** [mopemope/meghanada-emacs#18]
Hi!

Love your meghanada-emacs mode.  However, apparently it breaks error detection for Maven, at least in Emacs 24.5.1 (the version I'm using).  That version of Emacs (and probably others) already sets compilation-error-regexp-alist (actually, compilation-error-regexp-alist-alist) for maven, with a value that works.  When I use meghanada-emacs, it sets it to a value that does not work.  Here's the value that ships with Emacs in compile.el for maven:

```
"\\([^ \n]\\(?:[^\n :]\\| [^-/\n]\\|:[^ \n]\\)*?\\):\\[\\([0-9]+\\),\\([0-9]+\\)\\] "
```

**Comment by mopemope** [comment]
I have fixed it. Please check latest version.

**Comment by mopemope** [comment]
@dventimi I have fixed it. Please check latest version.
