### ISSUE TITLE
meghanada-jump-declaration when target not found

### ISSUE THREAD

**Issue by vkazanov** [mopemope/meghanada-emacs#21]
Sometimes (quite often unfortunately) `meghanada-jump-declaration` fails to find a proper point to jump to. When that happens it still tries to move the point to wherever the server points to, additionally moving the point by a single char.

I think that moving the point by single char is quite irritating here. 

I checked the emacs-side code - it *always* moves the point, event when the target is not found. Is that even correct? Maybe it is reasonable to not even parse the output of the server when it failed to find the proper target anyway?

**Comment by mopemope** [comment]
I have fixed it. Please check latest version.
