### ISSUE TITLE
can not complete members automatically

### ISSUE THREAD

**Issue by zbelial** [mopemope/meghanada-emacs#24]
company-meghanada complains "Symbol’s function definition is void: meghanada--what-word"
Adding a simple function, which is very similar to meghanada--what-symbol, as following can solve this problem
`          (defun meghanada--what-word()
            "TODO: FIX DOC ."
            (thing-at-point 'symbol))
`
Or changing meghanada--what-word in company-meghanada.el to meghanada--what-symbol can solve this problem, I think.

**Comment by mopemope** [comment]
I have fixed it. Please check latest version.

**Comment by zbelial** [comment]
Confirmed that it's fixed now, thanks.
