### ISSUE TITLE
Annotation processing support

### ISSUE THREAD

**Issue by douglarek** [mopemope/meghanada-emacs#33]
Some code generating library like Lombok(https://projectlombok.org/features/index.html) dependes on `Annotation Processing`, would meghanada like support this ?

**Comment by ninrod** [comment]
Yes, also interested in this.

**Comment by mopemope** [comment]
@douglarek Meghanada supported JSR 269: Pluggable Annotation Processing API.
![screenshot from 2017-03-10 01-00-14](https://cloud.githubusercontent.com/assets/22645/23758849/5953eb82-052e-11e7-85ac-607fbc2ea0bf.png)
