### ISSUE TITLE
eldoc functionality

### ISSUE THREAD

**Issue by jrab89** [mopemope/meghanada-emacs#34]
Would it be possible to implement eldoc support? It would be really nice to be able to see method/constructor signatures and variables' types, just by moving the point. For example, the [go-eldoc](https://github.com/syohex/emacs-go-eldoc) package does this for the Go programming language.

Thanks for the great package!

**Comment by mopemope** [comment]
@jrab89 I hava a plan el-doc feature.

**Comment by mopemope** [comment]
@jrab89 Supported el-doc.  Please check latest version.

**Comment by jrab89** [comment]
@mopemope works great, thank you!
