### ISSUE TITLE
Meghanada failing due to sequence returned from meghanada-ping

### ISSUE THREAD

**Issue by dakrone** [mopemope/meghanada-emacs#35]
When I run `meghanada-ping`, I occasionally get the following error:

```
Warning: (wrong-type-argument sequencep pong)
```

After a while though, ping works fine and returns the standard `pong`.

I am wondering if this is due to multiple gradle daemon's being started up?

**Comment by mopemope** [comment]
@dakrone Thanks. Fixed.
