### ISSUE TITLE
Can't install from melpa

### ISSUE THREAD

**Issue by sanderson-sfdc** [mopemope/meghanada-emacs#39]
On a Mac, with emacs 25.1.1, trying to install using package install from melpa.org/packages, version 20170402.2049

Invalid read syntax: "#"

**Comment by mopemope** [comment]
@sanderson-sfdc I couldn't reproduce it. Please check your init.el

**Comment by sanderson-sfdc** [comment]
Sorry, you're right, it was an error on my side.
