### ISSUE TITLE
Question: Support for projects not using Maven or Grade?

### ISSUE THREAD

**Issue by naclander** [mopemope/meghanada-emacs#46]
Lets say my project doesn't use Maven or Gradle, would I still be able to use meghanada efficiently?

I know the location of all my java files and dependencies. I have those files in a text file which I used to generate a TAGS file.

I'm wondering if meghanada supports this use case?

**Comment by mopemope** [comment]
@naclander You can use `.meghanada.conf`
see https://github.com/mopemope/meghanada-server/blob/master/docs/configuration.md
