### ISSUE TITLE
Sometimes C-w makes Emacs Crash.

### ISSUE THREAD

**Issue by songpeng** [mopemope/meghanada-emacs#47]
Hi, thanks for your meghanada. 
I use meghanada on MacOS Sierra, 10.12.5, Emacs Version 25.2, spacemacs configuration.
I came across twice when I in a java-mode (java-backend is meghanada), C-w for copy the codes makes Emacs Crash suddenly.
I never have this situation before.
Would you mind to give me some hints?
Thanks a lot!
           Songpeng

**Comment by mopemope** [comment]
@songpeng Thank you for your report.
Could you please check `*meghanada-server-log*` buffer or `/tmp/meghanada_server.log` ?

**Comment by songpeng** [comment]
Sorry, I cannot find /tmp/meghanada_server.log.... Also lost the server-log in Emacs when I come up with the situation. I just restart Emacs.
I think it might be the problem of my Emacs. I update emacs mac-port recently, and now it looks good.
Thanks a lot for your work so that I can stand on Emacs again.
Songpeng
