### ISSUE TITLE
Feature Request: Completions for `meghanada-run-task`

### ISSUE THREAD

**Issue by Yevgnen** [mopemope/meghanada-emacs#49]
Thanks for the great package. I'm new to Java and find meghanada is really awesome as an Emacs user. It would be nice if there are completions for `meghanada-run-task`. A simple implementation will be 

```
(interactive
   (list (completing-read
          "goals: "
          (list "validate" "initialize" "generate-sources" "process-sources"
                "generate-resources" "process-resources" "compile" "process-classes"
                "generate-test-sources" "process-test-sources" "generate-test-resources"
                "process-test-resources" "test-compile" "process-test-classes" "test"
                "prepare-package" "package" "pre-integration-test" "integration-test"
                "post-integration-test" "verify" "install" "deploy" "pre-clean" "clean"
                "post-clean" "pre-site" "site" "post-site" "site-deploy"))))
```

for maven. However, a more exquisite implementation should concern about

1. User input history like: `exec:java`(from [Maven Exec](http://www.mojohaus.org/exec-maven-plugin/usage.html))
2. Project based competition like maven and gradle.

😁How do you think about this?

**Comment by mopemope** [comment]
@Yevgnen Thank you for a good suggestion.
However, `meghanada-run-task` supports arbitrary multiple task (lifecycle) execution.
e.g. `clean install report`
So, I think it is difficult to complement the task (lifecycle).

If you want to trace the input history, Could you please use `<M-p>`.
