### ISSUE TITLE
: Error:meghanada-server process stopped

### ISSUE THREAD

**Issue by xianghx** [mopemope/meghanada-emacs#50]
Meghanada-Server Starting ...
error in process sentinel: meghanada--server-process-sentinel: Error:meghanada-server process stopped
error in process sentinel: Error:meghanada-server process stopped

```elsip
(use-package meghanada
  :ensure t
  :defer t
  :init
  (setq meghanada-server-install-dir (expand-file-name "~/.meghanada/"))
  (add-hook 'java-mode-hook 'meghanada-mode)
  :config
  (add-hook 'before-save-hook 'meghanada-code-beautify-before-save)
  )

`

so I use: 
$  cd myprojectroot/
$ java -jar ~/.meghanada/meghanada-0.7.10.jar
that's working.

**Comment by mopemope** [comment]
@xianghx Thank you for your report. Sever process launched from `shell-command` function. 
Could you please check `$PATH`? or use `exec-path-from-shell`.

**Comment by xianghx** [comment]
I use linux.
which cmd?

**Comment by mopemope** [comment]
Could you please try https://github.com/purcell/exec-path-from-shell?

**Comment by xianghx** [comment]
```elisp
(use-package exec-path-from-shell
  :ensure t
  :defer t
  :init
  (when (memq window-system '(mac ns x))
    (exec-path-from-shell-initialize)
    (exec-path-from-shell-copy-env "GOPATH"))

  :config
  (dolist (var '("SSH_AUTH_SOCK" "SSH_AGENT_PID" "GPG_AGENT_INFO" "LANG" "LC_CTYPE"))
    (add-to-list 'exec-path-from-shell-variables var))
  )
```
of course ,I hava it , but it doesn't  work

**Comment by xianghx** [comment]
I've used it before ， it's work.
Recently, I start use java, updated that's not work

**Comment by mopemope** [comment]
@xianghx Could you please try latest version ? And please check *Message* buffer.

**Comment by xianghx** [comment]
Configuring package meghanada...done
Download server module from https://dl.bintray.com/mopemope/meghanada/meghanada-0.7.11.jar. Please wait.
Wrote /home/xianghx/.meghanada/meghanada-0.7.11.jar
Downloaded server module from https://dl.bintray.com/mopemope/meghanada/meghanada-0.7.11.jar to /home/xianghx/.meghanada/meghanada-0.7.11.jar.
Configuring package flycheck...done
launch server cmd:java -Djava.net.preferIPv4Stack=true -Dmeghanada.format=sexp -Dmeghanada.skip.build.subprojects=true -Dmeghanada.javac.arg=-Xlint:all -ea -XX:+UseConcMarkSweepGC -XX:SoftRefLRUPolicyMSPerMB=50 -Xverify:none -Xms128m -Xmx4G -Dfile.encoding=UTF-8 -jar /home/xianghx/.meghanada/meghanada-0.7.11.jar -p 55555 
Meghanada-Server Starting ...
error in process sentinel: meghanada--server-process-sentinel: Error:meghanada-server process stopped
error in process sentinel: Error:meghanada-server process stopped

**Comment by xianghx** [comment]
xianghx@sky:~/myjava/Demo$ java -Djava.net.preferIPv4Stack=true -Dmeghanada.format=sexp -Dmeghanada.skip.build.subprojects=true -Dmeghanada.javac.arg=-Xlint:all -ea -XX:+UseConcMarkSweepGC -XX:SoftRefLRUPolicyMSPerMB=50 -Xverify:none -Xms128m -Xmx4G -Dfile.encoding=UTF-8 -jar /home/xianghx/.meghanada/meghanada-0.7.11.jar -p 55555
Invalid maximum heap size: -Xmx4G
The specified size exceeds the maximum representable size.
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.

**Comment by xianghx** [comment]
-Xmx4G  is too big   512m  enough.
we need defcustume it .

**Comment by xianghx** [comment]
It's work ,   thanks.
