### ISSUE TITLE
Beautify broken, it would seem.

### ISSUE THREAD

**Issue by pajatopmr** [mopemope/meghanada-emacs#51]
I copied the basic code from the README and modified the offset value to 8:

    (require 'meghanada)
    (add-hook 'java-mode-hook
              (lambda ()
                ;; meghanada-mode on
                (meghanada-mode t)
                (setq c-basic-offset 8)
                ;; use code format
                (add-hook 'before-save-hook 'meghanada-code-beautify-before-save)))

then read in a Hello World java file. Meghanada did indeed format the file but used a value of 2 (not 8). The value of c-basic-offset in the Main.java buffer was 8.  I looked at the Meghanada beautify code but don't see how the c-basic-offset is supposed to take effect.  I would be glad to debug further with a helpful hint or two.  For example, is the intent behind beautify to have the c-basic-offset applied by the server (java) or via the elisp code?

Can anyone say that custom indentation works for them?

My best guess after reading copious amounts of code that I ill understand on both the server and client is that custom indentation is not supported yet.  Could this be correct?

**Comment by hexingb** [comment]
I met this issue too. find no clue to fix this.

**Comment by mopemope** [comment]
@pajatopmr @hexingb  Meghanada does not code format in elisp.
see https://github.com/mopemope/meghanada-emacs#customize-code-formatter

**Comment by pajatopmr** [comment]
If this issue is resolved, it is not clear to me how to use it.  I applied the new readme code and still see 2 space indentation after changing c-basic-offset to 8.  Can you please update the README with settings that set the indentation to 4 so It is clear how to change it.

**Comment by hexingb** [comment]
Thank you @mopemope . You do a great job! Eclipse formatter is ok, though I still hope I can do code format in elisp. Do you have any plan to support this?

**Comment by pajatopmr** [comment]
@hexingb Thank you for clarifying the issue.  Now I am beginning to understand.  To customize `meghanada-mode` in ways commonly used by programmers leveraging Emacs, one must switch gears  and use XML rather than Elisp.  This may or may not be a problem.  I tend to think it is a problem but the jury is still out.  Seamy interfaces are to be avoided IMHO.

Tailoring the source code formatting done by `meghanada-mode` must be flexible and powerful and it seems like it should be accomplished easily by an Emacs lisp programmer.  It would appear that this is a future feature.  I  will spend some time trying to address this issue and will provide a repo link in this space if the effort proves fruitful.

@mopemope Thank you for laying the ground work with your efforts.  `meghanada-mode` is quite impressive and has a lot of promise for Java programmers with a love of Emacs.  I hope it will fill a vacuum that has existed for years and years and look forward to seeing more of your work.  Nicely done.

**Comment by hexingb** [comment]
Hi @pajatopmr . I made a workaround for myself. I cloned meghanada-server-0.7.10 and modified src/main/java/meghanada/formatter/JavaFormatter.java line 26 as "new Formatter(JavaFormatterOptions.builder().style(JavaFormatterOptions.Style.AOSP).build());". This gives me 4 space indentation. It's just a private hacking for myself, but I hope it may help you.

**Comment by pajatopmr** [comment]
@hexingb Thanks for doing this. It is the first step along the path towards complete formatting customization, a small but important step.

**Comment by vxcamiloxv** [comment]
If the user set `(setq c-basic-offset 4)` this config should be send to server (JavaFormatter.java), I think the indentation option should be configurable from emacs, I'm work with a team where all use InteliJ, and I tried with `meghanadaFormatter.xml` exported from eclipse (modified) and no get the expected result, my final solution is not use `meghanada-code-beautify-before-save` and I modified the indectation for the InteliJ project with `.dir-locals.el`:

```
((java-mode . ((eval . (progn
                              (make-local-variable 'arglist-intro)
                              (c-set-offset 'arglist-intro '++)
                              (make-local-variable 'arglist-cont-nonempty)
                              (c-set-offset 'arglist-cont-nonempty '(distopico:arglist-cont-nonempty-indentation c-lineup-gcc-asm-reg c-lineup-arglist))
                              (make-local-variable 'annotation-var-cont)
                              (c-set-offset 'annotation-var-cont 0)
                              (make-local-variable 'statement-cont)
                              (c-set-offset 'statement-cont '++)
                              )))))
```

**Comment by XO39** [comment]
Any news about this issue? I'm suffering from the same issue, and the `meghanadaFormatter.xml` solution didn't work for me either!
