### ISSUE TITLE
No autocompletion for static method

### ISSUE THREAD

**Issue by xiaogaozi** [mopemope/meghanada-emacs#55]
It seems like there's no autocompletion when use static method, e.g. `org.junit.Assert.assertEquals`. I try to invoke `meghanada-import-all` command, but there's no import statement appear.

FYI, I'm using Spacemacs with `meghanada-20170723.1724`.

**Comment by mopemope** [comment]
@xiaogaozi `meghanada-import-all` command does not support `static import`.
Contributions are extremely welcome!

**Comment by xiaogaozi** [comment]
I see, thanks for your reply.

**Comment by naclander** [comment]
@mopemope maybe we should leave this issue open so contributers know its a desired feature that needs to be implemented?

**Comment by mopemope** [comment]
I tried implementing it experimentally, please check the latest version.

**Comment by xiaogaozi** [comment]
Hi @mopemope, thanks for your efforts!

I've tried with 20180426 meghanada-emacs and 1.0.1 meghanada-server. Looks like the autocompletion is good, see below screenshot.

![screen shot 2018-04-27 at 12 45 10](https://user-images.githubusercontent.com/149645/39345065-f9287530-4a18-11e8-9b3c-63b3e4fd44be.png)

But `meghanada-import-all` command still doesn't work. And I notice some small change, `meghanada-optimize-import` command seems broken now.

**Comment by mopemope** [comment]
@xiaogaozi please use meghanada-import-at-point.

**Comment by xiaogaozi** [comment]
@mopemope I've tested with meghanada-emacs 20180521 and meghanada-server 1.0.3, the `meghanada-import-at-point` command works! But `meghanada-optimize-import` still broken.

**Comment by mopemope** [comment]
@xiaogaozi `meghanada-optimize-import` does not support static import.

**Comment by xiaogaozi** [comment]
@mopemope Sorry I didn't describe the problem clearly. I mean `meghanada-optimize-import` is broken, not only for static import, but also normal import. For example:

```java
import java.nio.file.Paths;
import lombok.extern.slf4j.Slf4j;
import java.util.List;
```

After run `meghanada-optimize-import` command I expect line 3 will put upward, i.e.:

```java
import java.nio.file.Paths;
import java.util.List;
import lombok.extern.slf4j.Slf4j;
```

But the real is nothing happened. And meghanada told me "Buffer is already formatted". After look the log (in `*meghanada-server-log*` buffer, I use Spacemacs), there's one warning:

```
[2018-06-01 14:02:52,572][WARN ][Session   : 464] it can not be optimized:A source has compile error.please fix it.
```

Looks like my Java code is broken. But I could totally confirm my code is compiled successfully.

If you could double check this problem really exist. I think we could create a new issue to track it. And this issue could be closed.

**Comment by mopemope** [comment]
@xiaogaozi OK. understood. I investigate in detail.
Could you add a new issue?

**Comment by xiaogaozi** [comment]
@mopemope I've created a new issue #106
