### ISSUE TITLE
Feature request: meghanada-optimize-import only handle Java source file

### ISSUE THREAD

**Issue by xiaogaozi** [mopemope/meghanada-emacs#56]
```elisp
  (add-hook 'java-mode-hook (lambda ()
                              (add-hook 'before-save-hook 'meghanada-optimize-import)))
```

I use these configuration so that optimize import statements automatically. But it seems like except Java source file, `meghanada-optimize-import` also process other files. For example, JavaScript has `import` statement too:

```javascript
import { xxx } from 'xxx';
```

`meghanada-optimize-import` will remove these lines incorrectly. I suggest only handle Java source file to prevent this situation from happening.

**Comment by mopemope** [comment]
@xiaogaozi I think you should do the following

```elisp
              (add-hook 'before-save-hook
                        (lambda ()
                          (when (string-suffix-p ".java" (buffer-name))
                            ... ))
```
