### ISSUE TITLE
Meghanada auto-completion line number display bug

### ISSUE THREAD

**Issue by naclander** [mopemope/meghanada-emacs#59]
I'm not sure what the best way to describe this is, so I have a screenshot:

![alt text](http://i.imgur.com/e5HWUNM.png "Logo Title Text 1")

To be fair, this could be a Company-mode specific bug. I am using the new emacs built-in line numbering mechanism that's available from the emacs master branch ( not linum or nlinum ).

**Comment by mopemope** [comment]
@naclander Thank you for your report. Perhaps  this is a bug in `company-mode`.

**Comment by naclander** [comment]
@mopemope It might be, but shouldn't this bug report be kept open until we figure it out?
