### ISSUE TITLE
[Feature Request] Show list of methods in class

### ISSUE THREAD

**Issue by naclander** [mopemope/meghanada-emacs#68]
A popular feature that other Java IDEs have is the ability to list the methods in the class of the current buffer. 

Clicking on the method should probably move the point to the location, in the buffer. Opinions on this feature?

**Comment by dakrone** [comment]
You can do this with semantic-mode and imenu (which has a parser for Java), that is what I use.

**Comment by naclander** [comment]
@dakrone that's a good solution, thanks. 

I guess this feature would be meghanada specific if it also showed the methods of the superclass? From what I understand semantic-mdoe and imenu can't do this as it requires Java semantics knowledge, so maybe this is something meghanada could have.

**Comment by dakrone** [comment]
Oh I definitely agree, it'd be much better to do it the "real" way that meghanada can, rather than parsing the file with elisp (the way that semantic does). It'd definitely be cool to have superclass info also, I'm definitely +1 if meghanada could do this!
