### ISSUE TITLE
can I stop the main execution after meghanada-exec-main

### ISSUE THREAD

**Issue by zhihuiFan** [mopemope/meghanada-emacs#74]
hi:
  after I start the main process with meghanada-exec-main, how can I stop it without restart the meghanada server?

Thanks

**Comment by dim3nsi4** [comment]
There is the command `meghanada-kill-running-process`. Is it what you are looking for ?

**Comment by zhihuiFan** [comment]
yes, it is.  Thanks you @dim3nsi4
