### ISSUE TITLE
Empty back jump cause hangs

### ISSUE THREAD

**Issue by an-sh** [mopemope/meghanada-emacs#86]
If i try to do a back jump when there is nothing to go back to, then the mode will get to a broken state.  Emacs starts hanging (i need to press C-g) on any further interaction with a server, but executing server restart command helps. Emacs 25.3 for mac, Meghanada version 0.9.1

**Comment by yangwen0228** [comment]
You can look at the "meghanada-server-log" buffer, maybe the server is parsing?

**Comment by an-sh** [comment]
```
error in process filter: meghanada--process-client-response: End of file during parsing
error in process filter: End of file during parsing
```

I get this consistently on any project. On linux this bug is present too.
