### ISSUE TITLE
Meghanada freezes

### ISSUE THREAD

**Issue by cactail** [mopemope/meghanada-emacs#87]
Hi
Recently I updated meghanada package. After that, I can't open any Java file, emacs freezes with this in the minibuffer:
`Contacting host: dl.bintray.com:443`

meghanada version = 0.9.1
GNU Emacs version = 25.3.1 (x86_64-pc-linux-gnu)

**Comment by seblemaguer** [comment]
Hello,

actually on my side it is worse as it makes my emacs crashing due to memory consumption. A temporary solution is to download directly the file and to put it in the .emacs.d/meghanada directory.

**Comment by azzamsa** [comment]
hi, I get the same problem.

I want to install fresh meghanada and emacs cunsuming lot memory, makes my wm hang.
```
Contacting host: dl.bintray.com:443
```

anyone know how to download it manually ?

I also notice that I don't have any maven instalation yet, as mentioned here https://github.com/mopemope/meghanada-emacs/issues/58.

**Comment by seblemaguer** [comment]
to download manually you can use wget like that:

```sh
export MEGHANADA_VERSION=0.9.2
wget https://dl.bintray.com/mopemope/meghanada/meghanada-$MEGHANADA_VERSION.jar -O ~/.emacs.d/meghanada/meghanada-$MEGHANADA_VERSION.jar
```

assuming that the target directory for meghanada ~/.emacs.d/meghanada which should be the case by default. Of course the version is defined by the version number in the used meghanada.el

**Comment by azzamsa** [comment]
Everything works fine after setting up maven, and run java app on maven project.
