### ISSUE TITLE
Meghanada's flycheck shows information groovy spits out about java linting

### ISSUE THREAD

**Issue by dakrone** [mopemope/meghanada-emacs#9]
I get the following lines showing up in my flycheck:

```
    -1  -1 info            Some input files additionally use or override a deprecated API. (meghanada)
    -1  -1 info            Some input files use unchecked or unsafe operations. (meghanada)
    -1  -1 info            Recompile with -Xlint:unchecked for details. (meghanada)
```

![screenshot from 2016-09-19 14-30-47](https://cloud.githubusercontent.com/assets/19060/18647957/ad391730-7e75-11e6-80a5-b23a45177cd2.png)

**Comment by mopemope** [comment]
groovy ??? I couldn't reproduce it.
Please check your emacs configuration and hook configuration.

**Comment by dakrone** [comment]
I think this might be something our gradle build outputs differently, so no problem!
