### ISSUE TITLE
Cannot install meghanada server using M-x meghanada-install-server

### ISSUE THREAD

**Issue by pseohy** [mopemope/meghanada-emacs#92]
Hello, I'm trying meghanada-mode to use emacs as a java IDE, and I am quite new to java.

After installing package using `M-x meghanada` mode, I've tried to install megnahada server using commad `M-x meghanada`, but it gets stuck at `Contacting host: dl.bintray.com:443`.

How can I get around this situation. Maybe the download server currently not available to use?

Thank you in advance.

**Comment by NybbTronio** [comment]
How did you solve this?
