### ISSUE TITLE
Show progress when meghanada downloading server module

### ISSUE THREAD

**Issue by azzamsa** [mopemope/meghanada-emacs#96]
Sometimes meghanada need a long time to download server module.  I think it will be nice if we can see some progress. So we know what's going on.

e.g precentage (80%) / process / [progress bar](https://github.com/Malabarba/spinner.el) :)

Thanks for this awesome package.

**Comment by azzamsa** [comment]
I waited meghanada downloading the module. I don't know why it took so long.
Turn out that the jar file is more than 40 Mb. 

So I am happier to download it [manually](https://dl.bintray.com/mopemope/meghanada/) then see the progress in browser :).

**Comment by mopemope** [comment]
@azzamsa I tried to display the progress.please check with the latest version.

**Comment by azzamsa** [comment]
```
downloaded 20% 9585990/45723158 bytes
downloaded 30% 13731253/45723158 bytes
downloaded 30% 13747600/45723158 bytes
downloaded 30% 13763947/45723158 bytes
downloaded 30% 13780294/45723158 bytes
downloaded 30% 13796641/45723158 bytes
downloaded 30% 13812988/45723158 bytes
downloaded 30% 13829335/45723158 bytes
downloaded 30% 13845682/45723158 bytes
```

That's great.

---

This is my first month with Meghanada. Java is not my primary language for building things. So I never got into research what Emacs package is great for doing java development.

This time. using Meghanada was great. automatic imports, great completion, integration with maven, etc.

Thanks lot for Meghanada. 
Thanks for your contribution to community. Thanks.
