### ISSUE TITLE
No processor claimed any of these annotations

### ISSUE THREAD

**Issue by liujoey** [mopemope/meghanada-emacs#97]
Building a new Spring-boot project. Constantly getting this warning:
```
No processor claimed any of these annotations: org.springframework.stereotype.Service,org.springframework.beans.factory.annotation.Autowired,org.springframework.web.bind.annotation.RequestMapping,org.springframework.web.bind.annotation.RestController,org.springframework.web.bind.annotation.CrossOrigin [5 times]
```
I do use Lombok but I feel this is a more generic problem and has nothing to do with Lombok.
Might be related to this issue:
https://github.com/spring-projects/spring-boot/issues/6421

In IntellJ IDEA I never see this type of warnings.

**Comment by mopemope** [comment]
Execute the following command and check `javacArg` value.
```
M-x meghanada-show-project
```
output:

```
...

Meghanada:
--------------------------------------------------------------------------------
meghanadaVersion: 1.0.1-xxx
...
javacArg: -Xlint:all,-processing
...
```
If it is not the same value, you can customize it as follows.

```
  (setq meghanada-javac-xlint "-Xlint:all,-processing")
```

**Comment by liujoey** [comment]
Yes that works. Thank you so much for helping.
