### ISSUE TITLE
Avoid downloading meghanada server jar if it already exists.

### ISSUE THREAD

**Issue by alexeiz** [mopemope/meghanada-emacs#98]
I'm behind a firewall and meghanada downloads always fail for me.  So I download jars manually and put them into the .emacs.d/meghanada directory.  However, the new setup always tries to download meghanada-%s.jar whether it already exists or not.  Please avoid doing that.  The fix is as simple as this:

```lisp
defun meghanada--run-setup ()
  "Setup meghanada server module."
  (let ((jar (meghanada--locate-setup-jar))
        (dest meghanada-server-install-dir)                                                                                   
        (dest-jar (meghanada--locate-server-jar)))
    (if (and (not file-exists-p dest-jar) (file-exists-p jar))
...
```

**Comment by azzamsa** [comment]
I downloaded all the jars manually. Cause I can't see downloading progress. It was fixed as https://github.com/mopemope/meghanada-emacs/commit/e469555b73bc1cd59d98326db715c5d72d42b41e.

In my experience. meghanada never try to download the jar if the current jar version same as meghanada version. eg meghanada 1.0.2 need meghanada-1.0.2.jar. If your current jar is meghanada-1.0.1.jar but you have slightly different version of meghanada. It will try to match the server jar. By downloading it.

PS: *second ago, I upgraded meghanada to 1.0.2 . I only have meghanada-1.0.1.jar. Then it automatically search for meghanada-1.0.2.jar. If you have  meghanada-1.0.2.jar already. then no action needed*

**Comment by mopemope** [comment]
@alexeiz hmmm. I could not reproduce it.
Please check latest version.

**Comment by alexeiz** [comment]
Interestingly, I can't reproduce it anymore either.  I think the issue can be closed then.

**Comment by mopemope** [comment]
OK. Thanks.
